### ISSUE TITLE
Question about the details of Table 3: Comparison with methods exploiting pre-trained models

### ISSUE THREAD

**Issue by judgingalready** [kakaobrain/miro#15]
Thanks for the nice work! As the large pretrained models become popular, the value of your work will be further reflected.

I am confused about the methods exploiting pre-trained models in Table 3. They don't seem to be in your code and don't be implemented in DomainBed. I think some of these methods are complicated to convert to domainbed, and the hyperparameter selection strategies of them are not clear.

So, could you please push the code of these methods or tell some details of implementing them in domainbed ?

Thank you very much again.

**Comment by khanrc** [comment]
Thank you for your interest in our work.

We're providing the command to reproduce Table 3 in https://github.com/kakaobrain/miro#experiments-with-various-backbones.
You can find related codes in https://github.com/kakaobrain/miro/blob/main/domainbed/networks/backbones.py and https://github.com/kakaobrain/miro/blob/main/domainbed/networks/ur_networks.py.

**Comment by judgingalready** [comment]
Thank you for your quick and positive reply!

I know various backbones are implemented in the code, which are very useful for me. However, perhaps my statement was incorrect. I would like to konw about the details of **algorithms** in other fields for different purposes (like LwF, DELTA) in Table 3 (not Table 2). There are not in algorithm.py and the hyperparameter selection strategies of them are not clear. So, could you please push the code of these methods (like LwF, DELTA) or tell some details of implementing them in domainbed ?

Sorry to bother you agian, thanks.

**Comment by khanrc** [comment]
You're right, the codes for Table 3 are not provided. We didn't include them during the refactoring process to make this repository public because they are mostly glue codes copied from the official repository. It would be difficult for us to add the codes at this point. However, if you have specific questions, please let us know, and we'll do our best to help. Please note that we have tried to use the official implementation whenever possible.

(I realized right after submitting my first comment that it was based on a misunderstanding. I deleted my comment, but you might have already seen it. Sorry for the inconvenience.)

**Comment by judgingalready** [comment]
I understand that and I will follow the official implementation of them. Thank you again!
