### ISSUE TITLE
Standard error of CLIP-ViT experiments

### ISSUE THREAD

**Issue by korts-lew** [kakaobrain/miro#6]
Hello, I make this issue to ask standard errors of experiments using CLIP-ViT.
Unlike the results reported using ResNet-50 and RegNet w/ SWAG, there is no standard errors for the results of CLIP-ViT 😢 
Can I get standard errors for it? (stds of 3 runs in PACS, VLCS, OfficeHome, TerraInc, DomainNet)
If it is impossible,  can you give me hyperparameters used for the experiments instead?

Thank you for your great work again

**Comment by khanrc** [comment]
Here is the results with standard errors of CLIP-ViT:

| Algorithm | PACS | VLCS | OfficeHome | TerraInc | DomainNet |
| - | :-: | :-: | :-: | :-: | :-: |
| ERM | 83.4 ± 0.5  |  75.9 ± 1.3  |  66.4 ± 0.5  |  35.3 ± 0.8  |  44.4 ± 0.6 |
| MIRO | 95.6 ± 0.8  |  82.2 ± 0.3  |  82.5 ± 0.1  |  54.3 ± 0.4  |  54.0 ± 0.3 | 

We omitted this due to lack of the space. Sorry for the inconvenience!

**Comment by korts-lew** [comment]
Thank you for your kind reply !! 😄
