### ISSUE TITLE
Question about the implementation of variance encoder

### ISSUE THREAD

**Issue by wenhao7841** [kakaobrain/miro#7]
It's a promising work for DG. But I got error when reproducing the result.
`
RuntimeError: The size of tensor a (96) must match the size of tensor b (2) at non-singleton dimension 0
`
which is due to the code in VarianceEncoder. I noticed that x in forward function is not used. Is there any problem with the code? 
https://github.com/kakaobrain/miro/blob/0661951de9e855fb8a8b464fbd5e4f4e5a066063/domainbed/algorithms/miro.py#L58

**Comment by khanrc** [comment]
Thank you for your interest in our work. 

It is correct code. We empirically designed VarianceEncoder and MeanEncoder as bias-only model and identity function, respectively. 
This code work fine in our environment. I think the problem is somewhere else. If you tell us your command, we will check it again.

**Comment by wenhao7841** [comment]
I'm sorry to bother you. 

I found my error was caused by using multi-gpus. I will stick to examine my code and follow this work. Thanx for your time!
